---
driver:
  name: vagrant
  customize:
    memory: 9000
    cpuexecutioncap: 90
    cpus: 1
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 41000, host: 40000}]
  - ["forwarded_port", {guest: 41001, host: 41001, protocol: "udp"}]
  - ["forwarded_port", {guest: 41002, host: 41002, protocol: "udp"}]
  - ["forwarded_port", {guest: 41003, host: 41003, protocol: "udp"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.0

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[dela::install]
      - recipe[dela::default]
    attributes:
         jdk_version: "7"
